### ISSUE TITLE
2FA instead of Single FA

### ISSUE THREAD

**Issue by TheCableGuy99** [yrccondor/wp-webauthn#45]
Hi,

I don't seem to be able to setup my Yubikey for a secondary factor authenticator.

The plugin appears to allow either password or my Yubikey. Can both be enabled?

Am I missing something? If it's not supported can you add it in please?

Thanks.

**Comment by yrccondor** [comment]
Hi,

This plug-in is designed for passwordless login, but not 2FA. Since WebAuthn is strong enough for replacing passwords, I recommand you fully switch to passwordless.

Anyway, for 2FA with WebAuthn, I recommand you use [Two Factor](https://wordpress.org/plugins/two-factor/) with [WebAuthn Provider for Two Factor](https://wordpress.org/plugins/two-factor-provider-webauthn/). These two plugins are not developed or maintained by me so please check them out before you install them.

**Comment by TheCableGuy99** [comment]
Fair enough, thanks for confirming that. I've gone with the Yubikey plugin instead. It works perfectly as I need.
