### ISSUE TITLE
WP-WebAuthn breaks the Reset Password page

### ISSUE THREAD

**Issue by stevapple** [yrccondor/wp-webauthn#52]
Reset Password page (typically `/wp-login.php?action=rp`) is used to set the new password. WP-WebAuthn affects the layout and hides the "Save Password" button, which breaks the functionality.

- Original:
<img width="1347" alt="截屏2023-03-14 17 49 14" src="https://user-images.githubusercontent.com/26525394/224964121-dd357a53-1841-4cf0-8448-ab141ca08185.png">

- WP-WebAuthn enabled:
<img width="1347" alt="截屏2023-03-14 17 48 44" src="https://user-images.githubusercontent.com/26525394/224964209-c73f8db9-e585-421e-9f02-be680433258b.png">

**Comment by yrccondor** [comment]
Thanks for reporting the issue. We will provide a fix soon.

**Comment by stevapple** [comment]
@yrccondor Is there any update?

**Comment by WolfBearGames** [comment]
@yrccondor It's 4 month later and the bug has still not been fixed. 
Additionally, I get a very strange behaviour when using the password reset form: Clicking on the Button to generate another password breaks the whole webserver?! 
I have installed the WP-Webauthn plugin on a shared hosting provider, and this seems to crash the whole server. Not only the Wordpress test site, but also all my other sites hosted by provider! None of my sites are reachable for about half an hour.
I can't provide any Debug information because there is none, the PHP Debug log does show nothing, and the server simply does not respond anymore.
I don't know how it is even possible for PHP Wordpress Plugin to take down a whole shared hosting environment.
I have tried with PHP Versions 8.2, 8.1 and 8.0 and the result is always the same.
I wanted to test on my local machine but the PHP installation does not include gmp so I could not test the plugin there.

**Comment by yrccondor** [comment]
@WolfBearGames Sorry for the late response ;-) I'm working on the plugin now so you can expect an update this week (hopefully)
I did a quick test on my local dev env and everything works well. That sounds weird - It may be caused by some PHP extensions. WP-WebAuthn doesn't not modify the password reset process but I'll look into this anyway.
